/*
 * Copyright 2024 Gonçalo Frade
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import JSONWebKey
@testable import JSONWebToken
import JSONWebSignature
import JSONWebEncryption
import XCTest

final class X5CValidatorTests: XCTestCase {
    
    func testValidateCertificate() async throws {
        let trusted =
        """
        -----BEGIN CERTIFICATE-----
        MIIBszCCAVmgAwIBAgIUXLTidX0XkEtc8XbnBkaFeF9JWGwwCgYIKoZIzj0EAwIw
        LzEQMA4GA1UECgwHYmVhdHQ4MzEbMBkGA1UEAwwSSm9zZSBTd2lmdCBSb290IENB
        MB4XDTI2MDMxNTEwMDkyOFoXDTM2MDMxMjEwMDkyOFowLzEQMA4GA1UECgwHYmVh
        dHQ4MzEbMBkGA1UEAwwSSm9zZSBTd2lmdCBSb290IENBMFkwEwYHKoZIzj0CAQYI
        KoZIzj0DAQcDQgAEgjwLVMAL24qav2t2nhe5Hwz5SHy3aggXbKZJmfGHZ8gHU7tr
        DlNnp2zrcCTJm9jRg9OZG1fDU8fN2+6V9NRQs6NTMFEwHQYDVR0OBBYEFK+oRfMo
        0Zvt2QQH6L9PssaiBjOLMB8GA1UdIwQYMBaAFK+oRfMo0Zvt2QQH6L9PssaiBjOL
        MA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSAAwRQIhAJFabGhIiKtK7pQ+
        1Nz1kTOFyALwW0rWvKkEsBOM6BRAAiAmjCwSbEr3Dx/czAXhaSDJgQutg0rsJR7Q
        4oMw9gSalg==
        -----END CERTIFICATE-----
        """
        
        let validToken = """
        eyJhbGciOiAiRVMyNTYiLCAidHlwIjogIkpXVCIsICJ4NWMiOiBbIk1JSUJyakNDQVZTZ0F3SUJBZ0lVQm1xV2tJSHYzVkVyNUhPV0tnYkc5YjJUQi9Nd0NnWUlLb1pJemowRUF3SXdOekVRTUE0R0ExVUVDZ3dIWW1WaGRIUTRNekVqTUNFR0ExVUVBd3dhU205elpTQlRkMmxtZENCSmJuUmxjbTFsWkdsaGRHVWdRMEV3SGhjTk1qWXdNekUxTVRBeE1ERTFXaGNOTXpZd016RXlNVEF4TURFMVdqQXpNUkF3RGdZRFZRUUtEQWRpWldGMGREZ3pNUjh3SFFZRFZRUUREQlpLYjNObElGTjNhV1owSUVObGNuUnBabWxqWVhSbE1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRTJnMEwyYmNRQVN3L0YzS3pJVTF0WkJDK0ZGSlE3RUs2b2F6ZytWNC96MUh6Qzc1QmY3ZDVXRVJPWENpNmdleWp5Z0JPeXBsWHdsam9YZC9OcGtIZ0RLTkNNRUF3SFFZRFZSME9CQllFRk9PVlI2U05oN3hLZ3p6aGo0OXZFT1l0TkVDaU1COEdBMVVkSXdRWU1CYUFGRkd5V29YQ3hxMUkzRVl2Y0dxMlAxZ09GRlFwTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUE3dDdOUkdUSVkzNjE4dEUvK1hERXdEdGFNaEVxdTBNT2FwMFd5SW9ueTRBaUVBeHBlR09wVlM0Ym56OE41R0JMVllaSDNObGN4TG05VlViZHZqVng4SXN1az0iLCAiTUlJQnV6Q0NBV0dnQXdJQkFnSVVRVXpRS1BOSlkrbVM4Mmx1VE50cXcvUFBSZ1l3Q2dZSUtvWkl6ajBFQXdJd0x6RVFNQTRHQTFVRUNnd0hZbVZoZEhRNE16RWJNQmtHQTFVRUF3d1NTbTl6WlNCVGQybG1kQ0JTYjI5MElFTkJNQjRYRFRJMk1ETXhOVEV3TURrMU0xb1hEVE0yTURNeE1qRXdNRGsxTTFvd056RVFNQTRHQTFVRUNnd0hZbVZoZEhRNE16RWpNQ0VHQTFVRUF3d2FTbTl6WlNCVGQybG1kQ0JKYm5SbGNtMWxaR2xoZEdVZ1EwRXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBU2hGVmQ0aFpRc01BNXU0ZC9OVHUzamxXaFpqMWZBY2h3YXdmL1pKV1RiSG5mc1k4T0w2SkhaQll1MFNzRWtZL0NIb1hSSWFSRXJIdFk0RE5TcXZTLzRvMU13VVRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSUnNscUZ3c2F0U054R0wzQnF0ajlZRGhSVUtUQWZCZ05WSFNNRUdEQVdnQlN2cUVYektOR2I3ZGtFQitpL1Q3TEdvZ1l6aXpBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQTFUZklDNi96RmUzRUMvZy9ZSjl0cjM3RlU4emJQenIrN1FvUHBGNUhCTkFDSUc1SFBqQlAzdVRCTEJUZFJtM3VuTTdyaUJzR0dwYWRSQ0JxSXlXN2VrcHUiLCAiTUlJQnN6Q0NBVm1nQXdJQkFnSVVYTFRpZFgwWGtFdGM4WGJuQmthRmVGOUpXR3d3Q2dZSUtvWkl6ajBFQXdJd0x6RVFNQTRHQTFVRUNnd0hZbVZoZEhRNE16RWJNQmtHQTFVRUF3d1NTbTl6WlNCVGQybG1kQ0JTYjI5MElFTkJNQjRYRFRJMk1ETXhOVEV3TURreU9Gb1hEVE0yTURNeE1qRXdNRGt5T0Zvd0x6RVFNQTRHQTFVRUNnd0hZbVZoZEhRNE16RWJNQmtHQTFVRUF3d1NTbTl6WlNCVGQybG1kQ0JTYjI5MElFTkJNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVnandMVk1BTDI0cWF2MnQybmhlNUh3ejVTSHkzYWdnWGJLWkptZkdIWjhnSFU3dHJEbE5ucDJ6cmNDVEptOWpSZzlPWkcxZkRVOGZOMis2VjlOUlFzNk5UTUZFd0hRWURWUjBPQkJZRUZLK29SZk1vMFp2dDJRUUg2TDlQc3NhaUJqT0xNQjhHQTFVZEl3UVlNQmFBRksrb1JmTW8wWnZ0MlFRSDZMOVBzc2FpQmpPTE1BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0NnWUlLb1pJemowRUF3SURTQUF3UlFJaEFKRmFiR2hJaUt0SzdwUSsxTnoxa1RPRnlBTHdXMHJXdktrRXNCT002QlJBQWlBbWpDd1NiRXIzRHgvY3pBWGhhU0RKZ1F1dGcwcnNKUjdRNG9NdzlnU2FsZz09Il19.eyJjb29sIjogdHJ1ZX0.JAOujM12ZgScbHF753aw9um1OgG8xSELsAa4Cc4muIdrBeSVbwEvfONBFMXHu6w2vR2Kc5UQREIHKMnlgd0Qdw
        """
        let validator = try X5CValidator(rootCertificates: [trusted])
        do {
            _ = try await validator.isValid(validToken)
        } catch {
            XCTFail("Function did throw with error: \(error)")
        }
    }
}
