name: Release Docs

on:
  push:
    tags: '*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Pages
      uses: actions/configure-pages@v5
        
    - name: Generate Docs
      run: |
        max_attempts=5
        count=0
        until xcodebuild docbuild -scheme jose-swift-docs -destination "platform=macOS" -derivedDataPath ./doccBuild OTHER_DOCC_FLAGS="--transform-for-static-hosting --output-path ./docc --hosting-base-path '/jose-swift'" ; do
        ((count++))
        if [ $count -eq $max_attempts ]; then
            echo "Documentation build failed after $max_attempts attempts."
            exit 1
        fi
        echo "Documentation build failed. Retrying attempt $((count+1))/$max_attempts..."
        sleep 5
        done

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docc

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs

    steps:
    - name: Deploy Docs
      uses: actions/deploy-pages@v4
