name: PR Check

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift test
  build_android:
    runs-on: macos-13
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Run unit tests
      uses: skiptools/swift-android-action@v2
      with:
        swift-version: 6.1
